version: '3'

services:

  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./vault/logs:/data/logs
      - ./vault/files:/data/files
      - ./vault/configs:/data/configs
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_PASSWORD}
      VAULT_TOKEN: ${VAULT_ROOT_PASSWORD}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200
    networks:
      - vault-network

  orchestrator:
    build:
      context: ./orchestrator
    container_name: orchestrator
    volumes:
      - ./orchestrator/files:/data/files
    environment:
      VAULT_ADDR: http://vault:8200
    networks:
      - vault-network
    command: tail -f /dev/null # keep container running

  app:
    build:
      context: ./app
    container_name: app
    volumes:
      - ./app/configs:/data/configs
    environment:
      VAULT_ADDR: http://vault:8200
    networks:
      - vault-network
    command: tail -f /dev/null # keep container running

networks:
  vault-network:
