version: '3'

services:

  vault:
    image: vault
    container_name: vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_PASSWORD}
      VAULT_TOKEN: ${VAULT_ROOT_PASSWORD}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://127.0.0.1:8200
    networks:
      - vault-network

  orchestrator:
    build:
      context: ./orchestrator
    container_name: orchestrator
    environment:
      VAULT_ADDR: http://vault:8200
    networks:
      - vault-network
    tmpfs:
      - /secrets      

  app:
    build:
      context: ./app
    container_name: app
    ports:
      - "8888:8080"
    environment:
      VAULT_ADDR: http://vault:8200
    networks:
      - vault-network

networks:
  vault-network:
