- hosts: localhost

  vars:
    vault_role_id: 024b931b-bf1c-42f5-98ac-1d072d8bae57
    vault_secret_id: 8ae055a8-1b58-54bb-4471-40bd623766d1
  tasks:
    - name: Git checkout
      git:
        repo: 'git@github.com:qdo-se/spring-vault.git'
        dest: /home/orchestrator-user/spring-vault

    - name: Gradle build
      shell: |
        cd /home/orchestrator-user/spring-vault
        gradle clean assemble

    # - name: Generate app's role and secret id 
    #   shell: |
    #     vault login $(vault write -field=token auth/approle/login role_id="{{ vault_role_id }}" secret_id="{{ vault_secret_id }}")
    #     vault read -field=role_id auth/approle/role/app/role-id

- hosts: all

  tasks:
    - name: Send jar to app container
      ansible.builtin.copy:
        src: /home/orchestrator-user/spring-vault/build/libs/spring-vault-1.0-SNAPSHOT.jar
        dest: /app
