- hosts: localhost

  tasks:
    - name: Git checkout
      git:
        repo: 'git@github.com:qdo-se/spring-vault.git'
        dest: /home/orchestrator-user/spring-vault

    - name: Gradle build
      shell: |
        cd /home/orchestrator-user/spring-vault
        gradle clean assemble

- hosts: all

  tasks:
    # - name: Send jar to app container
